### ISSUE TITLE
Interleaved topics dies 

### ISSUE THREAD

**Issue by marshall62** [marshall62/mathspring#286]
Dying in the method below because of a duplicate key violation

	at edu.umass.ckc.wo.db.DbTopics.addStudentInterleavedProblem(DbTopics.java:654)
	at edu.umass.ckc.wo.tutor.pedModel.InterleavedTopic.buildInterleavedProblemSet(InterleavedTopic.java:68)
	at edu.umass.ckc.wo.tutor.pedModel.TopicSelectorImpl.initializeTopic(TopicSelectorImpl.java:242)
	at edu.umass.ckc.wo.tutor.model.TopicModel.switchTopics(TopicModel.java:366)
	at edu.umass.ckc.wo.tutor.model.TopicModel.processBeginTopic(TopicModel.java:173)
	at edu.umass.ckc.wo.tutor.model.TopicModel.processInternalEvent(TopicModel.java:138)
	at edu.umass.ckc.wo.tutor.model.TopicModel.processEndOfTopic(TopicModel.java:262)
	at edu.umass.ckc.wo.tutor.model.TopicModel.processInternalEvent(TopicModel.java:141)
	at edu.umass.ckc.wo.tutor.model.TopicModel.processNextProblemEvent(TopicModel.java:295)
	at edu.umass.ckc.wo.tutor.model.TopicModel.processUserEvent(TopicModel.java:334)
	at edu.umass.ckc.wo.tutor.pedModel.BasePedagogicalModel.processInputResponseNextProblemInterventionEvent(BasePedagogicalModel.java:1010)
	at edu.umass.ckc.wo.tutor.pedModel.PedagogicalModel.processUserEvent(PedagogicalModel.java:329)

 public static void addStudentInterleavedProblem (Connection conn, int studId, int probId, int topicId, int position) throws SQLException {
        ResultSet rs=null;
        PreparedStatement stmt=null;
        try {
            String q = "insert into interleavedProblems (studId, probId, topicId, position, shown) values (?,?,?,?,0)";
            stmt = conn.prepareStatement(q);
            stmt.setInt(1, studId);
            stmt.setInt(2, probId);
            stmt.setInt(3, topicId);
            stmt.setInt(4, position);
            stmt.execute();
        }

        finally {
            if (rs != null)
                rs.close();
            if (stmt != null)
                stmt.close();
        }
    }

**Comment by marshall62** [comment]
Fixed.
